

const MAX_SCORE_CHANGE_MESSAGE = 100;
const MAX_SCORE_CHANGE_FIRST = 200;
const MAX_SCORE_CHANGE_SECOND = 300;

const MAX_COUNT_CHECKPOINT = 5;
const SUMA_VELOCITY = 0.5;
const MAX_SCORE_VELOCITY = 2000;

const ANGLE_GIRO = 45;
const VOLUME_COIN = 0.5;
const VOLUME_GAME = 0.3;
const VOLUME_JUMP = 0.5;
const VOLUME_TIME = 0.5;
const VOLUME_GIRO = 0.7;
const VOLUME_LOSE = 0.5;
const VOLUME_CHECKPOINT = 0.5;


const PORCENTAJE_MIN_AREA = 20;
const TILE_SIZE = 100;
const MIN_AREA = TILE_SIZE * (PORCENTAJE_MIN_AREA/100) ;

const MIN_BLOQUES_SHOW = 4;
const MAX_BLOQUES_SHOW = 5;

const MIN_TRAMOS = 3;

const MAX_TIME_SHOW_RANDOM_MESSAGE = 5000;

const INITIAL_VELOCIDAD = 3;

const PASO_MITAD = 50;

const DURATION_DESTROY = 1000;
const DURATION_DEAD = 1500;
const SIZE_AFTER_DEAD = 50;
export {
    MAX_SCORE_CHANGE_FIRST,
    MAX_SCORE_CHANGE_SECOND,
    MAX_TIME_SHOW_RANDOM_MESSAGE,
    SIZE_AFTER_DEAD,
    DURATION_DEAD,
    PASO_MITAD,
    DURATION_DESTROY, 
    INITIAL_VELOCIDAD,
    MIN_TRAMOS,
    MAX_SCORE_CHANGE_MESSAGE,
    MAX_COUNT_CHECKPOINT,
    ANGLE_GIRO ,
    VOLUME_COIN,
    VOLUME_GAME,
    VOLUME_TIME,
    VOLUME_GIRO,
    VOLUME_JUMP,
    VOLUME_LOSE,
    VOLUME_CHECKPOINT,
    MIN_AREA,
    MIN_BLOQUES_SHOW,
    MAX_BLOQUES_SHOW,
    SUMA_VELOCITY,
    MAX_SCORE_VELOCITY
}